const BOOK_STATE = {
  WAITING: 'WAITING',
  RENTALED: 'RENTALED',
  RESERVATED: 'RESERVATED',
  MISSED: 'MISSED',
};

const RESERVATION_STATE = {
  WAITING: 'WAITING',
  ACTIVATED: 'ACTIBATED',
  CANCELED: 'CANCELED',
};

module.exports = {
  BOOK_STATE,
  RESERVATION_STATE,
};
