const BOOK_STATE = {
  WAITING: 'WAITING',
  RENTALED: 'RENTALED',
  RESERVATED: 'RESERVATED',
  MISSED: 'MISSED',
};

const RESERVATION_STATE = {
  WAITING: 'WAITING',
  ACTIVATED: 'ACTIBATED',
  CANCELED: 'CANCELED',
};

const KAFKA_CLIENT_ID = {
  INTERNSHIP_JINYEONG: 'internship-jinyeong',
};

const KAFKA_TOPIC = {
  DUE_DATE_NOTIFICATION: 'due-date-notification',
};

const KAFKA_CONSUMER_GROUP_ID = {
  DUE_DATE_MAILER: 'due-date-mailer',
};

module.exports = {
  BOOK_STATE,
  RESERVATION_STATE,
  KAFKA_CLIENT_ID,
  KAFKA_TOPIC,
  KAFKA_CONSUMER_GROUP_ID,
};
