const ERROR_CODE = {
  // Bad Request
  BAD_REQUEST: 'BAD_REQUEST',
  REQUIRED_INPUT_NULL: 'REQUIRED_INPUT_NULL',
  BAD_USER_INPUT: 'BAD_USER_INPUT',
  SIGNUP_EMAIL_REDUPLICATED: 'SIGNUP_EMAIL_REDUPLICATED',
  DB_INVALID_REFERENCE: 'DB_INVALID_REFERENCE',
  INVALID_INPUT_DATA: 'INVALID_INPUT_DATA',
  NOT_AVAILABLE_REQUEST: 'NOT_AVAILABLE_REQUEST',
  INVALID_INPUT_TYPE: 'INVALID_INPUT_TYPE',
  INVALID_EMAIL_REGEX: 'INVALID_EMAIL_REGEX',
  INVALID_PASSWORD_REGEX: 'INVALID_PASSWORD_REGEX',
  INVALID_CONTACT_REGEX: 'INVALID_CONTACT_REGEX',

  // Unauthorized
  NEED_AUTHENTICATE: 'NEED_AUTHENTICATE',
  INVALID_TOKEN: 'INVALID_TOKEN',
  INVALID_LOGIN_ACCESS: 'INVALID_LOGIN_ACCESS',
  INVALID_ADMIN_SECRET_CODE: 'INVALID_ADMIN_SECRET_CODE',
  DUPLICATE_LOGIN: 'DUPLICATE_LOGIN',

  // Forbidden
  NEED_PERMISSION: 'NEED_PERMISSION',
  FORBIDDEN_USER_REQUEST: 'FORBIDDEN_USER_REQUEST',
  NOT_ALLOWED_OTHERS: 'NOT_ALLOWED_OTHERS',
  THIS_ROLE_NOT_AUTHORIZED: 'THIS_ROLE_NOT_AUTHORIZED',
  NOT_AUTHORIZED: 'NOT_AUTHORIZED',

  // Not Found
  NON_RESOURCE_EXIST: 'NON_RESOURCE_EXIST',

  // Unexpected Error
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  DB_TRANSACTION_ERROR: 'DB_TRANSACTION_ERROR',
};

const BOOK_STATE = {
  WAITING: 'WAITING',
  RENTALED: 'RENTALED',
  RESERVATED: 'RESERVATED',
  MISSED: 'MISSED',
};

const RESERVATION_STATE = {
  WAITING: 'WAITING',
  ACTIVATED: 'ACTIBATED',
  CANCELED: 'CANCELED',
};

const KAFKA_CLIENT_ID = {
  INTERNSHIP_JINYEONG: 'internship-jinyeong',
};

const KAFKA_TOPIC = {
  DUE_DATE_NOTIFICATION: 'due-date-notification',
};

const KAFKA_CONSUMER_GROUP_ID = {
  DUE_DATE_MAILER: 'due-date-mailer',
};

module.exports = {
  ERROR_CODE,
  BOOK_STATE,
  RESERVATION_STATE,
  KAFKA_CLIENT_ID,
  KAFKA_TOPIC,
  KAFKA_CONSUMER_GROUP_ID,
};
