const ID_MAX_LENGTH = 10
const ID_MIN_LENGTH = 5
const PASSWORD_MIN_LENGTH = 8
const PASSWORD_MAX_LENGTH = 12
const NAME_MIN_LENGTH = 2
const NAME_MAX_LENGTH = 7

export {
  ID_MAX_LENGTH,
  ID_MIN_LENGTH,
  PASSWORD_MIN_LENGTH,
  PASSWORD_MAX_LENGTH,
  NAME_MIN_LENGTH,
  NAME_MAX_LENGTH,
}
