module.exports = {
  async up(queryInterface) {
    await queryInterface.bulkInsert('Books', [
      {
        title: '자유로울 것',
        author: '임경선',
        publisher: '위즈덤하우스',
        page: 287,
        statusCode: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '젊은 베르테르의 슬픔',
        author: '요한 볼프강 폰 괴테',
        publisher: '민음사',
        page: 244,
        statusCode: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Principles (원칙)',
        author: 'Ray Dalio (레이 달리오)',
        publisher: '한빛비즈',
        page: 715,
        statusCode: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '위대한 기업에 투자하라',
        author: '워렌 버핏',
        publisher: '굿모닝북스',
        page: 715,
        statusCode: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Do it! 점프 투 파이썬',
        author: '박응용',
        publisher: '이지스퍼블리싱',
        page: 356,
        statusCode: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '모던 자바스크립트 Deep Dive',
        author: '이웅모',
        publisher: '위키북스',
        page: 922,
        statusCode: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Clean Code (클린 코드)',
        author: '로버트 C. 마틴',
        publisher: '인사이트',
        page: 584,
        statusCode: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '데일 카네기 자기관리론',
        author: '데일 카네기',
        publisher: '현대지성',
        page: 422,
        statusCode: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '진짜 쓰는 실무 엑셀',
        author: '전진권',
        publisher: '제이펍',
        page: 508,
        statusCode: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '비전공자도 이해할 수 있는 AI 지식',
        author: '박상길',
        publisher: '반니',
        page: 440,
        statusCode: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '비전공자를 위한 이해할 수 있는 IT지식',
        author: '최원영',
        publisher: '티더블유아이지',
        page: 240,
        statusCode: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '1일 1로그 100일완성 IT지식',
        author: '브라이언 W. 커니핸',
        publisher: '인사이트(insight)',
        page: 560,
        statusCode: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '혼자 공부하는 파이썬',
        author: '윤인성',
        publisher: '한빛미디어',
        page: 460,
        statusCode: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '만들면서 배우는 파이썬과 40개의 작품들',
        author: '장문철',
        publisher: '엔써북',
        page: 348,
        statusCode: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '혼자 공부하는 머신러닝 + 딥러닝',
        author: '박해선',
        publisher: '한빛미디어',
        page: 580,
        statusCode: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '실무에 바로 쓰는 일잘러의 보고서 작성법',
        author: '김마라',
        publisher: '제이펍',
        page: 256,
        statusCode: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Do it! HTML+CSS+자바스크립트 웹 표준의 정석',
        author: '고경희',
        publisher: '이지스퍼블리싱',
        page: 648,
        statusCode: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '헤드 퍼스트 디자인 패턴',
        author: '에릭 프리먼, 엘리자베스 롭슨',
        publisher: '한빛미디어',
        page: 656,
        statusCode: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '이것이 취업을 위한 코딩 테스트다 with 파이썬',
        author: '나동빈',
        publisher: '한빛미디어',
        page: 604,
        statusCode: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '혼자 공부하는 C 언어',
        author: '서현우',
        publisher: '한빛미디어',
        page: 664,
        statusCode: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '맛있는 디자인 포토샵&일러스트레이터 CC 2022',
        author: '박정아, 윤이사라',
        publisher: '한빛미디어',
        page: 544,
        statusCode: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '퇴근 후 스마트스토어로 투잡하기',
        author: '박하나',
        publisher: '비제이퍼블릭(BJ퍼블릭)',
        page: 508,
        statusCode: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Java의 정석',
        author: '남궁성',
        publisher: '도우출판',
        page: 1022,
        statusCode: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '프로그래머의 뇌',
        author: '펠리너 헤르만스',
        publisher: '제이펍',
        page: 272,
        statusCode: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '면접을 위한 CS 전공지식 노트',
        author: '주홍철',
        publisher: '길벗',
        page: 292,
        statusCode: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '도메인 주도 개발 시작하기',
        author: '최범균',
        publisher: '한빛미디어',
        page: 356,
        statusCode: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '유튜브 영상 편집을 위한 프리미어 프로',
        author: '조블리',
        publisher: '제이펍',
        page: 452,
        statusCode: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ], {});
  },

  async down(queryInterface) {
    await queryInterface.bulkDelete('Books', null, {});
  },
};
