version: '3'

services:
  internship-postgres:
    container_name: internship-postgres
    image: postgres:12.0
    restart: always
    ports:
      - '6432:5432'
    environment:
      - POSTGRES_USER=intern
      - POSTGRES_PASSWORD=intern
      - POSTGRES_DB=intern
    volumes:
      - internship-pgdb:/var/lib/postgresql/data

  internship-zookeeper:
    container_name: internship-zookeeper
    image: confluentinc/cp-zookeeper:5.2.2
    hostname: zookeeper
    ports:
      - '3181:3181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
    volumes:
      - internship-zk-data:/var/lib/zookeeper/data
      - internship-zk-log:/var/lib/zookeeper/log

  internship-kafka:
    container_name: internship-kafka
    image: confluentinc/cp-enterprise-kafka:5.2.2
    hostname: kafka
    ports:
      - '8092:8092'
      - '8093:8093'
    depends_on:
      - internship-zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2182
      KAFKA_LISTENERS: INTERNAL://kafka:8092,EXTERNAL://kafka:8093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:8092,EXTERNAL://localhost:8093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    volumes:
      - internship-kafka-data:/var/lib/kafka/data

volumes:
  internship-pgdb:
  internship-zk-data:
  internship-zk-log:
  internship-kafka-data:
