// 서비스 정책 관련 상수
module.exports = {
  RENTAL_PERIOD: 7,
  EXTEND_PERIOD: 7,
  MAX_RENTAL_NUM: 3,
  MAX_EXTEND_COUNT: 3,
  DAYS_BEFORE_RETURN: 3,
  BOOK_REGIGISTATION_LIMIT: 5,
  PAGE_DEFAULT: 1,
  PER_PAGE: 10,
};
