// user module mutation-types
const SET_LOGIN_FORM_MODAL_VISIBLE = 'SET_LOGIN_FORM_MODAL_VISIBLE'
const SET_MY_INFO = 'SET_MY_INFO'
const REMOVE_MY_INFO = 'REMOVE_MY_INFO'
const SET_RESPONSE_INFO = 'SET_RESPONSE_INFO'
const RESET_RESPONSE_INFO = 'RESET_RESPONSE_INFO'
const UPDATE_NICKNAME = 'UPDATE_NICKNAME'

// weather module mutation-types
const SET_CURRENT_REGION_INFO = 'SET_CURRENT_REGION_INFO'
const SET_CURRENT_WEATHER_DATA = 'SET_CURRENT_WEATHER_DATA'
const SET_ONE_CALL_API_DATA = 'SET_ONE_CALL_API_DATA'
const SET_RESPONSE_ERROR_INFO = 'SET_RESPONSE_ERROR_INFO'
const RESET_RESPONSE_ERROR_INFO = 'RESET_RESPONSE_ERROR_INFO'
const SET_CURRENT_COORDS = 'SET_CURRENT_COORDS'
const SET_SEARCH_COORDS = 'SET_SEARCH_COORDS'

export {
  SET_LOGIN_FORM_MODAL_VISIBLE,
  SET_MY_INFO,
  REMOVE_MY_INFO,
  UPDATE_NICKNAME,
  SET_RESPONSE_INFO,
  RESET_RESPONSE_INFO,
  SET_CURRENT_WEATHER_DATA,
  SET_ONE_CALL_API_DATA,
  SET_CURRENT_REGION_INFO,
  SET_RESPONSE_ERROR_INFO,
  RESET_RESPONSE_ERROR_INFO,
  SET_CURRENT_COORDS,
  SET_SEARCH_COORDS,
}
