// user module mutation-types
const SET_LOGIN_FORM_MODAL_VISIBLE = 'SET_LOGIN_FORM_MODAL_VISIBLE'
const SET_MY_INFO = 'SET_MY_INFO'
const REMOVE_MY_INFO = 'REMOVE_MY_INFO'
const SET_RESPONSE_INFO = 'SET_RESPONSE_INFO'
const RESET_RESPONSE_INFO = 'RESET_RESPONSE_INFO'
// weather module mutation-types
const SET_CURRENT_WEATHER_DATA = 'SET_CURRENT_WEATHER_DATA'
export {
  SET_LOGIN_FORM_MODAL_VISIBLE,
  SET_MY_INFO,
  REMOVE_MY_INFO,
  SET_RESPONSE_INFO,
  RESET_RESPONSE_INFO,
  SET_CURRENT_WEATHER_DATA,
}
